"""empty message

Revision ID: 00bdc70be8c4
Revises: 0eee163dfe7f
Create Date: 2025-07-09 19:07:06.235429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00bdc70be8c4'
down_revision = '0eee163dfe7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('project_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('owner_id')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('project_ibfk_1'), 'user', ['owner_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('created_at')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
